name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: actions/setup-ruby@v2
      with:
        ruby-version: 2.6.6

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Run Tests
      run: |
        bundle exec rails db:migrate RAILS_ENV=test
        bundle exec rspec # Replace with your test command

